// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 确​定
		 */
		confirm: string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 创​建
		 */
		create: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 启​用
		 */
		enable: string
		/**
		 * 禁​用
		 */
		disable: string
		/**
		 * 重​命​名
		 */
		rename: string
		/**
		 * 删​除
		 */
		'delete': string
	}
	command: {
		/**
		 * 重​载​插​件
		 */
		reload: string
		/**
		 * 创​建​代​码​文​件
		 */
		create_code_file: string
		/**
		 * 在​代​码​编​辑​器​中​打​开
		 */
		open_in_code_editor: string
		/**
		 * 编​辑​代​码​块
		 */
		edit_code_block: string
		/**
		 * 打​开​c​s​s​片​段​管​理​器
		 */
		open_css_snippet_manager: string
		/**
		 * 打​开​设​置​视​图
		 */
		open_settings_view: string
		/**
		 * 快​速​配​置
		 */
		quick_config: string
	}
	notice: {
		/**
		 * 文​件​名​不​能​为​空
		 */
		file_name_validate: string
		/**
		 * 自​定​义​文​件​名​必​须​包​含​扩​展​名
		 */
		file_name_with_extension_validate: string
		/**
		 * 文​件​已​存​在
		 */
		file_already_exists: string
		/**
		 * 文​件​重​命​名​成​功​，​{​p​a​t​h​}
		 * @param {string} path
		 */
		rename_file_success: RequiredParams<'path'>
		/**
		 * 文​件​创​建​成​功​，​{​p​a​t​h​}
		 * @param {string} path
		 */
		create_file_success: RequiredParams<'path'>
		/**
		 * 文​件​ ​{​f​i​l​e​N​a​m​e​}​ ​已​删​除
		 * @param {string} fileName
		 */
		file_deleted: RequiredParams<'fileName'>
	}
	view: {
		snippets: {
			/**
			 * 创​建​于​ ​{​d​a​t​e​}
			 * @param {string} date
			 */
			created: RequiredParams<'date'>
			/**
			 * 最​后​修​改​于​ ​{​d​a​t​e​}
			 * @param {string} date
			 */
			modified: RequiredParams<'date'>
			/**
			 * 没​有​发​现​代​码​片​段
			 */
			no_snippets: string
			/**
			 * 新​建​代​码​片​段
			 */
			create_new_snippet: string
			/**
			 * 排​序
			 */
			sort_by: string
			/**
			 * 文​件​名​(​A​-​Z​)
			 */
			sort_by_name_asc: string
			/**
			 * 文​件​名​(​Z​-​A​)
			 */
			sort_by_name_desc: string
			/**
			 * 修​改​时​间​(​旧​-​>​新​)
			 */
			sort_by_mtime_asc: string
			/**
			 * 修​改​时​间​(​新​-​>​旧​)
			 */
			sort_by_mtime_desc: string
			/**
			 * 创​建​时​间​(​旧​-​>​新​)
			 */
			sort_by_ctime_asc: string
			/**
			 * 创​建​时​间​(​新​-​>​旧​)
			 */
			sort_by_ctime_desc: string
			/**
			 * 批​量​操​作
			 */
			batch_operation: string
			/**
			 * 启​用​所​有​代​码​片​段
			 */
			enable_all_snippets: string
			/**
			 * 禁​用​所​有​代​码​片​段
			 */
			disable_all_snippets: string
			/**
			 * 重​新​加​载​代​码​片​段
			 */
			reload_snippets: string
			/**
			 * 启​用​代​码​片​段
			 */
			enable_snippet: string
			/**
			 * 禁​用​代​码​片​段
			 */
			disable_snippet: string
			/**
			 * 重​命​名​代​码​片​段
			 */
			rename_snippet: string
			/**
			 * 删​除​代​码​片​段
			 */
			delete_snippet: string
			/**
			 * 确​定​要​删​除​代​码​片​段​ ​{​f​i​l​e​N​a​m​e​}​ ​吗​？
			 * @param {string} fileName
			 */
			delete_snippet_message: RequiredParams<'fileName'>
			/**
			 * 无​需​输​入​后​缀​ ​.​c​s​s
			 */
			file_modal_message: string
			/**
			 * 请​输​入​并​开​始​搜​索​.​.​.
			 */
			search_placeholder: string
			/**
			 * 区​分​大​小​写
			 */
			case_sensitive: string
			/**
			 * 清​除​搜​索
			 */
			clear_search: string
		}
	}
	modal: {
		createCodeFile: {
			/**
			 * 创​建​代​码​文​件
			 */
			header: string
			/**
			 * 文​件​类​型
			 */
			file_type: string
			/**
			 * 选​择​文​件​类​型
			 */
			file_type_placeholder: string
			/**
			 * 文​件​名
			 */
			file_name: string
			/**
			 * 请​输​入​文​件​名
			 */
			file_name_placeholder: string
			/**
			 * 文​件​名​（​包​含​扩​展​名​）
			 */
			file_name_with_extension: string
			/**
			 * 输​入​文​件​名​（​包​含​扩​展​名​）
			 */
			file_name_with_extension_placeholder: string
			/**
			 * 预​览
			 */
			preview: string
			/**
			 * 创​建​后​打​开​文​件
			 */
			open_file_after_create: string
			/**
			 * 文​件​夹​路​径
			 */
			folder_path: string
		}
		editCodeBlock: {
			/**
			 * 编​辑​代​码​块
			 */
			header: string
		}
	}
	setting: {
		tabs: {
			/**
			 * 渲​染
			 */
			renderer: string
			/**
			 * 会​话
			 */
			session: string
			/**
			 * 编​辑
			 */
			editor: string
			/**
			 * 扩​展
			 */
			extend: string
			/**
			 * 关​于
			 */
			about: string
		}
		/**
		 * 查​看​<​a​ ​h​r​e​f​=​'​h​t​t​p​s​:​/​/​d​o​c​s​.​r​a​v​e​n​h​o​g​w​a​r​t​s​.​t​o​p​/​o​b​s​i​d​i​a​n​-​a​c​e​-​c​o​d​e​-​e​d​i​t​o​r​/​'​ ​t​a​r​g​e​t​=​'​_​b​l​a​n​k​'​>​w​i​k​i​文​档​<​/​a​>​了​解​更​多​功​能
		 */
		desc: string
		supportExtensions: {
			/**
			 * 注​册​文​件​类​型
			 */
			name: string
			/**
			 * 注​册​后​，​点​击​文​件​将​直​接​在​代​码​编​辑​器​中​打​开​，​修​改​后​需​重​载​插​件
			 */
			desc: string
			/**
			 * 输​入​文​件​扩​展​名​，​按​下​E​n​t​e​r​键​添​加
			 */
			placeholder: string
		}
		snippetsManager: {
			/**
			 * c​s​s​片​段​管​理
			 */
			name: string
			/**
			 * c​s​s​片​段​管​理​按​钮​是​否​在​底​部​状​态​栏​显​示​，​修​改​后​需​重​载​插​件
			 */
			desc: string
		}
		lightTheme: {
			/**
			 * 亮​色​主​题
			 */
			name: string
			/**
			 * 代​码​编​辑​器​的​亮​色​主​题
			 */
			desc: string
		}
		darkTheme: {
			/**
			 * 暗​色​主​题
			 */
			name: string
			/**
			 * 代​码​编​辑​器​的​暗​色​主​题
			 */
			desc: string
		}
		keyboard: {
			/**
			 * 键​盘
			 */
			name: string
			/**
			 * 代​码​编​辑​器​的​键​盘​风​格
			 */
			desc: string
		}
		showLineNumbers: {
			/**
			 * 行​号
			 */
			name: string
			/**
			 * 显​示​行​号
			 */
			desc: string
		}
		fontSize: {
			/**
			 * 字​体​大​小
			 */
			name: string
			/**
			 * 代​码​编​辑​器​的​字​体​大​小
			 */
			desc: string
		}
		fontFamily: {
			/**
			 * 字​体
			 */
			name: string
			/**
			 * 代​码​编​辑​器​使​用​的​字​体
			 */
			desc: string
			/**
			 * 选​择​或​输​入​字​体​名​称
			 */
			placeholder: string
		}
		tabSize: {
			/**
			 * 缩​进​宽​度
			 */
			name: string
			/**
			 * t​a​b​键​的​宽​度
			 */
			desc: string
		}
		showPrintMargin: {
			/**
			 * 打​印​边​距
			 */
			name: string
			/**
			 * 显​示​代​码​编​辑​器​中​的​竖​线
			 */
			desc: string
		}
		showInvisibles: {
			/**
			 * 不​可​见​字​符
			 */
			name: string
			/**
			 * 在​代​码​编​辑​器​中​显​示​不​可​见​字​符
			 */
			desc: string
		}
		displayIndentGuides: {
			/**
			 * 缩​进​参​考​线
			 */
			name: string
			/**
			 * 在​代​码​编​辑​器​中​显​示​缩​进​参​考​线
			 */
			desc: string
		}
		showFoldWidgets: {
			/**
			 * 折​叠​部​件
			 */
			name: string
			/**
			 * 在​代​码​编​辑​器​中​显​示​折​叠​部​件
			 */
			desc: string
		}
		embedMaxHeight: {
			/**
			 * 嵌​入​代​码​块​最​大​高​度
			 */
			name: string
			/**
			 * 嵌​入​代​码​块​的​最​大​高​度​(​单​位​p​x​)​，​超​过​该​高​度​将​出​现​滚​动​条
			 */
			desc: string
		}
		wrap: {
			/**
			 * 自​动​换​行
			 */
			name: string
			/**
			 * 在​代​码​编​辑​器​中​启​用​自​动​换​行​，​超​过​编​辑​器​宽​度​的​代​码​将​自​动​换​行​显​示
			 */
			desc: string
		}
		minimap: {
			enabled: {
				/**
				 * 启​用​缩​略​图
				 */
				name: string
				/**
				 * 在​编​辑​器​右​侧​显​示​缩​略​图​，​方​便​快​速​导​航​代​码
				 */
				desc: string
			}
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 确定
		 */
		confirm: () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 创建
		 */
		create: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 启用
		 */
		enable: () => LocalizedString
		/**
		 * 禁用
		 */
		disable: () => LocalizedString
		/**
		 * 重命名
		 */
		rename: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
	}
	command: {
		/**
		 * 重载插件
		 */
		reload: () => LocalizedString
		/**
		 * 创建代码文件
		 */
		create_code_file: () => LocalizedString
		/**
		 * 在代码编辑器中打开
		 */
		open_in_code_editor: () => LocalizedString
		/**
		 * 编辑代码块
		 */
		edit_code_block: () => LocalizedString
		/**
		 * 打开css片段管理器
		 */
		open_css_snippet_manager: () => LocalizedString
		/**
		 * 打开设置视图
		 */
		open_settings_view: () => LocalizedString
		/**
		 * 快速配置
		 */
		quick_config: () => LocalizedString
	}
	notice: {
		/**
		 * 文件名不能为空
		 */
		file_name_validate: () => LocalizedString
		/**
		 * 自定义文件名必须包含扩展名
		 */
		file_name_with_extension_validate: () => LocalizedString
		/**
		 * 文件已存在
		 */
		file_already_exists: () => LocalizedString
		/**
		 * 文件重命名成功，{path}
		 */
		rename_file_success: (arg: { path: string }) => LocalizedString
		/**
		 * 文件创建成功，{path}
		 */
		create_file_success: (arg: { path: string }) => LocalizedString
		/**
		 * 文件 {fileName} 已删除
		 */
		file_deleted: (arg: { fileName: string }) => LocalizedString
	}
	view: {
		snippets: {
			/**
			 * 创建于 {date}
			 */
			created: (arg: { date: string }) => LocalizedString
			/**
			 * 最后修改于 {date}
			 */
			modified: (arg: { date: string }) => LocalizedString
			/**
			 * 没有发现代码片段
			 */
			no_snippets: () => LocalizedString
			/**
			 * 新建代码片段
			 */
			create_new_snippet: () => LocalizedString
			/**
			 * 排序
			 */
			sort_by: () => LocalizedString
			/**
			 * 文件名(A-Z)
			 */
			sort_by_name_asc: () => LocalizedString
			/**
			 * 文件名(Z-A)
			 */
			sort_by_name_desc: () => LocalizedString
			/**
			 * 修改时间(旧->新)
			 */
			sort_by_mtime_asc: () => LocalizedString
			/**
			 * 修改时间(新->旧)
			 */
			sort_by_mtime_desc: () => LocalizedString
			/**
			 * 创建时间(旧->新)
			 */
			sort_by_ctime_asc: () => LocalizedString
			/**
			 * 创建时间(新->旧)
			 */
			sort_by_ctime_desc: () => LocalizedString
			/**
			 * 批量操作
			 */
			batch_operation: () => LocalizedString
			/**
			 * 启用所有代码片段
			 */
			enable_all_snippets: () => LocalizedString
			/**
			 * 禁用所有代码片段
			 */
			disable_all_snippets: () => LocalizedString
			/**
			 * 重新加载代码片段
			 */
			reload_snippets: () => LocalizedString
			/**
			 * 启用代码片段
			 */
			enable_snippet: () => LocalizedString
			/**
			 * 禁用代码片段
			 */
			disable_snippet: () => LocalizedString
			/**
			 * 重命名代码片段
			 */
			rename_snippet: () => LocalizedString
			/**
			 * 删除代码片段
			 */
			delete_snippet: () => LocalizedString
			/**
			 * 确定要删除代码片段 {fileName} 吗？
			 */
			delete_snippet_message: (arg: { fileName: string }) => LocalizedString
			/**
			 * 无需输入后缀 .css
			 */
			file_modal_message: () => LocalizedString
			/**
			 * 请输入并开始搜索...
			 */
			search_placeholder: () => LocalizedString
			/**
			 * 区分大小写
			 */
			case_sensitive: () => LocalizedString
			/**
			 * 清除搜索
			 */
			clear_search: () => LocalizedString
		}
	}
	modal: {
		createCodeFile: {
			/**
			 * 创建代码文件
			 */
			header: () => LocalizedString
			/**
			 * 文件类型
			 */
			file_type: () => LocalizedString
			/**
			 * 选择文件类型
			 */
			file_type_placeholder: () => LocalizedString
			/**
			 * 文件名
			 */
			file_name: () => LocalizedString
			/**
			 * 请输入文件名
			 */
			file_name_placeholder: () => LocalizedString
			/**
			 * 文件名（包含扩展名）
			 */
			file_name_with_extension: () => LocalizedString
			/**
			 * 输入文件名（包含扩展名）
			 */
			file_name_with_extension_placeholder: () => LocalizedString
			/**
			 * 预览
			 */
			preview: () => LocalizedString
			/**
			 * 创建后打开文件
			 */
			open_file_after_create: () => LocalizedString
			/**
			 * 文件夹路径
			 */
			folder_path: () => LocalizedString
		}
		editCodeBlock: {
			/**
			 * 编辑代码块
			 */
			header: () => LocalizedString
		}
	}
	setting: {
		tabs: {
			/**
			 * 渲染
			 */
			renderer: () => LocalizedString
			/**
			 * 会话
			 */
			session: () => LocalizedString
			/**
			 * 编辑
			 */
			editor: () => LocalizedString
			/**
			 * 扩展
			 */
			extend: () => LocalizedString
			/**
			 * 关于
			 */
			about: () => LocalizedString
		}
		/**
		 * 查看<a href='https://docs.ravenhogwarts.top/obsidian-ace-code-editor/' target='_blank'>wiki文档</a>了解更多功能
		 */
		desc: () => LocalizedString
		supportExtensions: {
			/**
			 * 注册文件类型
			 */
			name: () => LocalizedString
			/**
			 * 注册后，点击文件将直接在代码编辑器中打开，修改后需重载插件
			 */
			desc: () => LocalizedString
			/**
			 * 输入文件扩展名，按下Enter键添加
			 */
			placeholder: () => LocalizedString
		}
		snippetsManager: {
			/**
			 * css片段管理
			 */
			name: () => LocalizedString
			/**
			 * css片段管理按钮是否在底部状态栏显示，修改后需重载插件
			 */
			desc: () => LocalizedString
		}
		lightTheme: {
			/**
			 * 亮色主题
			 */
			name: () => LocalizedString
			/**
			 * 代码编辑器的亮色主题
			 */
			desc: () => LocalizedString
		}
		darkTheme: {
			/**
			 * 暗色主题
			 */
			name: () => LocalizedString
			/**
			 * 代码编辑器的暗色主题
			 */
			desc: () => LocalizedString
		}
		keyboard: {
			/**
			 * 键盘
			 */
			name: () => LocalizedString
			/**
			 * 代码编辑器的键盘风格
			 */
			desc: () => LocalizedString
		}
		showLineNumbers: {
			/**
			 * 行号
			 */
			name: () => LocalizedString
			/**
			 * 显示行号
			 */
			desc: () => LocalizedString
		}
		fontSize: {
			/**
			 * 字体大小
			 */
			name: () => LocalizedString
			/**
			 * 代码编辑器的字体大小
			 */
			desc: () => LocalizedString
		}
		fontFamily: {
			/**
			 * 字体
			 */
			name: () => LocalizedString
			/**
			 * 代码编辑器使用的字体
			 */
			desc: () => LocalizedString
			/**
			 * 选择或输入字体名称
			 */
			placeholder: () => LocalizedString
		}
		tabSize: {
			/**
			 * 缩进宽度
			 */
			name: () => LocalizedString
			/**
			 * tab键的宽度
			 */
			desc: () => LocalizedString
		}
		showPrintMargin: {
			/**
			 * 打印边距
			 */
			name: () => LocalizedString
			/**
			 * 显示代码编辑器中的竖线
			 */
			desc: () => LocalizedString
		}
		showInvisibles: {
			/**
			 * 不可见字符
			 */
			name: () => LocalizedString
			/**
			 * 在代码编辑器中显示不可见字符
			 */
			desc: () => LocalizedString
		}
		displayIndentGuides: {
			/**
			 * 缩进参考线
			 */
			name: () => LocalizedString
			/**
			 * 在代码编辑器中显示缩进参考线
			 */
			desc: () => LocalizedString
		}
		showFoldWidgets: {
			/**
			 * 折叠部件
			 */
			name: () => LocalizedString
			/**
			 * 在代码编辑器中显示折叠部件
			 */
			desc: () => LocalizedString
		}
		embedMaxHeight: {
			/**
			 * 嵌入代码块最大高度
			 */
			name: () => LocalizedString
			/**
			 * 嵌入代码块的最大高度(单位px)，超过该高度将出现滚动条
			 */
			desc: () => LocalizedString
		}
		wrap: {
			/**
			 * 自动换行
			 */
			name: () => LocalizedString
			/**
			 * 在代码编辑器中启用自动换行，超过编辑器宽度的代码将自动换行显示
			 */
			desc: () => LocalizedString
		}
		minimap: {
			enabled: {
				/**
				 * 启用缩略图
				 */
				name: () => LocalizedString
				/**
				 * 在编辑器右侧显示缩略图，方便快速导航代码
				 */
				desc: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
